# Swift 5.0, SwiftLint 0.25.1
reporter: xcode
disabled_rules:
  - todo
excluded:
  - Carthage
  - Pods
  - vendor
line_length: 300
file_length: 1000
function_body_length:
  - 50
  - 100
type_body_length:
  - 300
  - 500
type_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
    error: 60
identifier_name:
  min_length:
    warning: 1
  max_length:
    warning: 40
    error: 60
identifier_name:
  min_length:
    warning: 1
  max_length:
    warning: 41
    error: 60
