reporter: xcode
enabled_rules:
  - force_unwrapping
disabled_rules:
  - todo
excluded:
  - Carthage
  - Pods
  - vendor
line_length: 200
file_length: 1000
function_body_length:
  - 50
  - 100
type_body_length:
  - 300
  - 500
variable_name:
  excluded:
    - id
    - ok
function_parameter_count:
  - 6
  - 8
