# reporter: xcode10.2 and swift 5.0
disabled_rules:
  - todo
excluded:
  - Carthage
  - Pods
  - vendor
line_length: 300
file_length: 1000
function_body_length:
  - 50
  - 100
type_body_length:
  - 300
  - 500
variable_name:
  excluded:
    - id