#!/bin/bash

if [[ "$CIRCLECI" == 'true' ]]; then
    REPO_SLUG="$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"
    PR_NUMBER="$(./scripts/pr_number)"
else
    REPO_SLUG="$TRAVIS_REPO_SLUG"
    [[ "$TRAVIS_PULL_REQUEST" != 'false' ]] && PR_NUMBER="$TRAVIS_PULL_REQUEST"
fi

echo "REPO_SLUG = $REPO_SLUG"
echo "PR_NUMBER = $PR_NUMBER"

if [[ -z "$PR_NUMBER" ]]; then
    echo 'Not in a Pull Request, skip Linter'
else
    swiftlint lint --reporter json > swiftlint-report.json || false
    bundle exec linterbot $REPO_SLUG $PR_NUMBER < swiftlint-report.json
fi
