#!/bin/bash

if [[ "$CIRCLECI" == 'true' ]]; then
    REPO_SLUG="$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"
else
    REPO_SLUG="$TRAVIS_REPO_SLUG"
fi

PR_NUMBER="$(./scripts/pr_number)"

echo "REPO_SLUG = $REPO_SLUG"
echo "PR_NUMBER = $PR_NUMBER"

if [[ -z "$PR_NUMBER" ]]; then
    echo 'Not in a Pull Request, skip Linter'
else
    swiftlint lint --reporter json > swiftlint-report.json || false
    bundle exec linterbot $REPO_SLUG $PR_NUMBER < swiftlint-report.json
fi
