#!/bin/bash

if [[ "$CI" != 'true' ]]; then
    echo 'Exporting build environment variables...'
    export SDK='iphonesimulator10.0'
    export WORKSPACE='RealmS.xcworkspace'
    export DESTINATION='OS=10.0,name=iPhone 6'
fi

xcodebuild build \
    -workspace "$WORKSPACE" \
    -scheme "PodTest" \
    -sdk "$SDK" \
    -destination "$DESTINATION" \
    -derivedDataPath build \
    ONLY_ACTIVE_ARCH=YES \
    -configuration Debug

exit ${PIPESTATUS[0]}
