#!/bin/bash

if [[ -z "$CIRCLE_PR_NUMBER" ]]; then
    if [[ -z "$CI_PULL_REQUEST" ]]; then
        URL="https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pulls?head=$CIRCLE_PROJECT_USERNAME:$CIRCLE_BRANCH"
        RESULT="$(curl -X GET -u $GITHUB_ACCESS_TOKEN:x-oauth-basic $URL | jq -r '.[0].url')"
        [[ "$RESULT" == 'null' ]] && CI_PULL_REQUEST='' || CI_PULL_REQUEST="${RESULT//\"}"
    fi
    CIRCLE_PR_NUMBER="$(basename "$CI_PULL_REQUEST")"
fi

echo "$CIRCLE_PR_NUMBER"
