#!/bin/bash

bundle install --path=vendor/bundle --jobs 4 --retry 3

brew tap Homebrew/bundle
brew bundle

setup_cocoapods() {
    echo 'Setup cocoapods...'
    bundle exec pod setup --silent > /dev/null
    bundle exec pod repo update --silent
    bundle exec pod install
}

bundle exec pod install || setup_cocoapods
