#!/bin/bash

echo "Branch name: $SRC_BRANCH"

[[ "$SRC_BRANCH" == master ]] && exit 0

for PREFIX in feature bugfix hotfix release; do
    [[ "$SRC_BRANCH" == $PREFIX/* ]] && exit 0
done

echo "Branch name does not pass convention."
exit 1
